# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_progress',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
